import pyautogui
import time
import random

time.sleep(2)

list = [
    "i love go for glass",
    "tuff",
    "i love deca",
    "deca rocks",
    "help me with my prepared event",
    "gambling time",
    "i love to gamble",
    "ahhhh",
    "gambleeeeee",
    "Wow",
    "I HATE ARYAN PATEL",
    "go for glahh",
    "I ate Dee",
    "glass me up",
    "roleplay champion",
    "money moves only",
    "judge pls",
    "pitch me baby",
    "i am the ceo",
    "marketinggggg",
    "glahhh for glass",
    "deca is my personality",
    "ready to gamble",
    "i crave competition",
    "business casual always",
    "i live for cluster exams",
    "help i lost my visuals",
    "glassy vibes",
    "i’m peaking",
    "it’s crunch time",
    "brain go brrrr",
    "i want the blue glass",
    "cash flow crisis incoming",
    "i need a 20 pager NOW",
    "where's my deca medal",
    "craving roleplay",
    "someone feed me visuals",
    "shark tank who?",
    "i pitched in my dream",
    "judge was biased",
    "glass is eternal",
    "i want to go internationals",
    "we deca now",
    "CEO of business",
    "i ate a rubric",
    "rubric tastes like success",
    "my visuals are edible",
    "entrepreneur me",
    "let me gamble or i will explode",
    "supply and demand BABY",
    "glass>gold",
    "deca in my veins",
    "call me mr. prepared",
    "wowowowowow",
    "AHHHHHHH",
    "just did a SWOT in real life",
    "someone get me a judge",
    "ppt me",
    "pdf is love",
    "ppt is life",
    "don’t talk to me i’m brainstorming",
    "deca sleep schedule",
    "i studied the rubric for fun",
    "deca has consumed me",
    "why is aryan like that",
    "i’m in my innovation era",
    "GAMBLEEE",
    "probability of success = 100%",
    "business plan? never heard of it",
    "glass > all other materials",
    "where is my cluster score",
    "marketing king",
    "deca queen",
    "im a business beast",
    "glahhhhh",
    "visuals are a personality trait",
    "judge didn’t smile i’m doomed",
    "my 7 minute timer rules me",
    "i pitch better than i talk",
    "roleplay more like soulplay",
    "i just SWOT analyzed my lunch",
    "deca hunger games",
    "i want to win internationals by accident",
    "glassed up on a tuesday",
    "pitch please",
    "feed me a prompt",
    "judge ignored my visuals 😭",
    "rubric royalty",
    "i have no script but lots of passion",
    "i gamble between slides",
    "cluster exam ate me alive",
    "deca but unhinged",
    "deca mode: activated",
    "i need help with my 11 page script",
    "business? i barely know her",
    "let’s run a SWOT real quick",
    "my marketing plan is vibes only",
    "glassy mcglassface",
    "gamble time never ends",
    "deca dreams and nightmares",
    "i love roleplaying with strangers",
    "DECA stands for Don’t Ever Challenge Aryan",
    "i’m not okay but i’m still competing",
    "give me glass or give me death",
    "i visualized too hard",
    "deca is life",
    "glahhh for gold",
    "gambling is my passion",
    "i need a roleplay partner",
    "business me up",
    "money money money",
    "i love glass so much",
    "give me that cluster exam",
    "who took my pencils",
    "i miss internationals",
    "help me write my 20 pager",
    "entrepreneurial mindset time",
    "aaaaaa",
    "i challenge you to a gamble",
    "where’s aryan",
    "deee was tasty",
    "LET’S GOOOO",
    "glass is gas",
    "i just pitched to a judge in my sleep",
    "i just bribed a judge with vibes",
    "my visuals are copyrighted",
    "deca ruined my sleep cycle",
    "i lost to a freshman again",
    "i gamble to cope",
    "ppt is my therapist",
    "my partner ghosted me mid-pitch",
    "i roleplay harder than i breathe",
    "i wrote a 20 pager at 3am",
    "business is my love language",
    "i named my fish deca",
    "i gave my judge eye contact and trauma",
    "give me the rubric or give me death",
    "i'm on my fourth energy drink",
    "my pitch has 6 plot twists",
    "i SWOT analyzed my relationships",
    "my cluster score was a hate crime",
    "i drafted my plan in crayon",
    "i trained for DECA like it's the olympics",
    "my suit is glued to my soul",
    "just elbowed someone for a table",
    "i cried in the prep room",
    "deca is my villain origin story",
    "my partner is a powerpoint",
    "i pitched in an elevator and cried after",
    "i lost my voice yelling ‘let’s deca’",
    "i judged my judge harder than they judged me",
    "my briefcase is emotional support",
    "i bet my GPA on this pitch",
    "i gave a business plan with zero math",
    "someone stole my visuals and my dignity",
    "this is not just roleplay. this is war.",
    "i am emotionally attached to my category",
    "deca fried my frontal lobe",
    "i used my brain for my 20 pager",
    "aryan patel rizz",
    "i visualized my dreams too hard",
    "i flirted with the judge for points",
    "i failed my final but won deca",
    "i just pitched an evil startup on accident",
    "i ran out of buzzwords and cried",
    "capitalism is my aesthetic",
    "my idea is legally questionable",
    "i deca even in my dreams",
    "my pencil snapped mid-roleplay",
    "deca gave me stockholm syndrome",
    "i used monopoly money as a prop",
    "my roleplay had lore",
    "i made a SWOT meme in my deck",
    "judge laughed. i did not.",
    "i’m addicted to entrepreneurship",
    "my pitch was legally binding",
    "i prepared my visuals in microsoft paint",
    "deca has absorbed my personality",
    "i named my binder greg",
    "just SWOT-analyzed my existence",
    "my business plan was an apology letter",
    "i roleplayed as my alter ego",
    "deca made me feral",
    "my suit smells like ambition",
    "i just pitched a pyramid scheme",
    "my product is illegal in 3 countries",
    "i brought snacks for the judge",
    "judge sneezed, i panicked",
    "i drew my visuals in sharpie",
    "deca unlocked my final form",
    "my pitch was sponsored by delusion",
    "i made eye contact and forgot my name",
    "i cried at awards and i wasn’t even called",
    "my cluster exam gaslit me",
    "i pitched from the heart and nothing else",
    "my deck has no stats, just vibes",
    "i wrote a haiku in my script",
    "i introduced myself with a pun and regret",
    "deca gave me PTSD: PowerPoint Traumatic Stress Disorder",
    "i just got humbled by a sophomore",
    "my startup is a bakery for frogs",
    "i said synergy 14 times in 7 minutes",
    "i used glitter on my visuals. worth it.",
    "i judged other teams silently",
    "my prompt was spiritual warfare",
    "i prepared by watching shark tank on 2x speed",
    "my roleplay turned into a therapy session",
    "i drew a graph with no axis labels",
    "deca gave me character development",
    "my judge blinked and i forgot my pitch",
    "i sold vibes and made profit",
    "i’m not in deca. deca is in me.",
    "i put my GPA on the line for this pitch",
    "my visuals were held together by hope",
    "i used glitter glue on my SWOT chart",
    "deca is short for ‘demonic energy consuming adolescents’",
    "i pitched a haunted coffee shop",
    "my prep room was a void of despair",
    "i trademarked my roleplay name",
    "i yelled return on investment and hoped for the best",
    "judge said ‘interesting’ and i knew i failed",
    "i made eye contact and time slowed down",
    "my business plan included interpretive dance",
    "i made a pun and the judge wrote it down",
    "i forgot my opening line so i sang it",
    "i pitched a business that doesn’t exist yet",
    "my partner dipped mid-pitch for snacks",
    "i wrote my 20 pager on the bus",
    "deca is my roman empire",
    "i prayed to the cluster gods",
    "i pitched a candle that screams", "rizz",
    "deca is why i fear PowerPoint", "apple", "car", "house", "dog", "cat", "book", "table", "water", "sun", "tree", "school", "chair", "food", "friend", "music", "bird", "phone", "computer", "window", "door", "shirt", "shoe", "hat", "road", "city", "store", "light", "river", "mountain", "flower", "ocean", "rain", "snow", "wind", "fire", "earth", "family", "game", "movie", "story", "pen", "paper", "clock", "ball", "key", "bag", "cup", "bed", "mirror", "wall", "floor", "ceiling", "lamp", "candle", "box", "plant", "tree", "leaf", "branch", "root",
"sky", "star", "moon", "planet", "cloud", "stone", "rock", "sand", "path", "hill",
"train", "bus", "bike", "truck", "plane", "boat", "ship", "bridge", "tunnel", "street",
"park", "garden", "field", "barn", "farm", "animal", "cow", "horse", "pig", "sheep",
"chicken", "goat", "duck", "fish", "whale", "shark", "dolphin", "seal", "crab", "octopus",
"teacher", "student", "doctor", "nurse", "police", "firefighter", "artist", "actor", "singer", "dancer",
"driver", "cook", "baker", "waiter", "painter", "writer", "poet", "scientist", "engineer", "pilot",
"president", "king", "queen", "prince", "princess", "soldier", "lawyer", "judge", "coach", "referee",
"glove", "scarf", "jacket", "belt", "sock", "pants", "shorts", "sweater", "suit", "tie",
"toy", "doll", "puzzle", "block", "crayon", "paint", "brush", "string", "rope", "chain",
"coin", "money", "bank", "card", "ticket", "letter", "note", "envelope", "stamp", "gift",
"box", "ring", "necklace", "bracelet", "earring", "watch", "calendar", "map", "photo", "picture",
"art", "statue", "music", "song", "beat", "rhythm", "voice", "sound", "noise", "melody", "rizz", "testing stuff", "sup", "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon", 
"lime", "mango", "nectarine", "orange", "papaya", "peach", "pear", "pineapple", "plum", "pomegranate", 
"raspberry", "strawberry", "tangerine", "watermelon", "apricot", "blackberry", "blueberry", "cantaloupe", "coconut", "cranberry", 
"dragonfruit", "guava", "jackfruit", "lychee", "mulberry", "olive", "passionfruit", "persimmon", "quince", "starfruit", 
"tomato", "ugli fruit", "yuzu", "zucchini", "broccoli", "carrot", "cabbage", "cauliflower", "spinach", "lettuce", 
"arugula", "kale", "chard", "parsley", "cilantro", "basil", "thyme", "rosemary", "sage", "oregano", 
"mint", "dill", "fennel", "leek", "onion", "garlic", "shallot", "chive", "ginger", "turmeric", 
"beet", "radish", "parsnip", "turnip", "rutabaga", "potato", "sweet potato", "yam", "cassava", "taro", 
"butternut squash", "acorn squash", "pumpkin", "spaghetti squash", "cucumber", "celery", "zucchini blossom", "pea", "green bean", "soybean", 
"chickpea", "lentil", "black bean", "pinto bean", "kidney bean", "navy bean", "adzuki bean", "mung bean", "fava bean", "edamame", 
"bread", "butter", "cheese", "milk", "cream", "yogurt", "ice cream", "eggs", "omelet", "scrambled eggs", 
"pancake", "waffle", "toast", "bagel", "croissant", "muffin", "donut", "biscuit", "scone", "tortilla", 
"pizza", "pasta", "spaghetti", "macaroni", "lasagna", "ravioli", "gnocchi", "fettuccine", "penne", "linguine", 
"rice", "brown rice", "white rice", "sushi rice", "wild rice", "quinoa", "barley", "oats", "millet", "couscous", 
"breadstick", "crouton", "cracker", "pretzel", "popcorn", "chips", "nachos", "taco", "burrito", "quesadilla", 
"enchilada", "tamale", "chimichanga", "fajita", "empanada", "arepa", "pupusa", "salsa", "guacamole", "sour cream", 
"steak", "hamburger", "cheeseburger", "hot dog", "sausage", "bacon", "ham", "turkey", "chicken", "duck", 
"goose", "lamb", "veal", "pork", "beef", "venison", "rabbit", "salmon", "tuna", "trout", 
"mackerel", "sardine", "anchovy", "cod", "haddock", "halibut", "swordfish", "shark", "octopus", "squid", 
"clam", "mussel", "scallop", "oyster", "lobster", "crab", "shrimp", "prawn", "crawfish", "abalone", 
"cake", "pie", "cookie", "brownie", "cupcake", "pudding", "custard", "gelato", "sorbet", "trifle", 
"cheesecake", "tiramisu", "cannoli", "macaron", "eclair", "profiterole", "churro", "funnel cake", "beignet", "pavlova", 
"caramel", "chocolate", "vanilla", "strawberry shortcake", "apple pie", "pumpkin pie", "pecan pie", "key lime pie", "banoffee pie", "bread pudding", 
"coffee", "tea", "espresso", "latte", "cappuccino", "mocha", "americano", "macchiato", "chai", "matcha", 
"green tea", "black tea", "oolong", "herbal tea", "rooibos", "bubble tea", "lemonade", "orange juice", "apple juice", "grape juice", 
"milkshake", "smoothie", "soda", "cola", "ginger ale", "root beer", "tonic water", "sparkling water", "mineral water", "iced tea", 
"cocktail", "mocktail", "margarita", "mojito", "martini", "bloody mary", "sangria", "pina colada", "whiskey sour", "old fashioned", 
"beer", "lager", "ale", "stout", "porter", "cider", "mead", "wine", "red wine", "white wine", 
"rosé", "champagne", "prosecco", "sherry", "port", "vermouth", "rum", "vodka", "gin", "tequila", 
"whiskey", "bourbon", "brandy", "cognac", "absinthe", "sake", "soju", "baijiu", "arak", "ouzo", 
"computer", "laptop", "tablet", "smartphone", "keyboard", "mouse", "monitor", "printer", "scanner", "webcam", 
"microphone", "speaker", "headphones", "earbuds", "charger", "battery", "hard drive", "flash drive", "cloud storage", "server", 
"router", "modem", "ethernet", "wi-fi", "bluetooth", "satellite", "drone", "robot", "AI", "VR headset", 
"AR glasses", "smartwatch", "fitness tracker", "camera", "DSLR", "mirrorless camera", "tripod", "gimbal", "flash", "lens", 
"car", "truck", "bus", "motorcycle", "bicycle", "scooter", "skateboard", "rollerblades", "train", "subway", 
"tram", "ferry", "boat", "yacht", "sailboat", "canoe", "kayak", "raft", "ship", "airplane", 
"helicopter", "jet", "glider", "paraglider", "hot air balloon", "spaceship", "rocket", "satellite", "submarine", "hovercraft", 
"house", "apartment", "cottage", "villa", "mansion", "castle", "hut", "tent", "cabin", "igloo", 
"yurt", "palace", "pagoda", "mosque", "church", "temple", "synagogue", "cathedral", "skyscraper", "tower", 
"bridge", "road", "highway", "street", "alley", "avenue", "boulevard", "driveway", "parking lot", "garage", 
"garden", "park", "forest", "jungle", "desert", "beach", "mountain", "valley", "canyon", "waterfall", 
"lake", "river", "pond", "ocean", "sea", "island", "peninsula", "volcano", "glacier", "iceberg", 
"sun", "moon", "star", "planet", "asteroid", "comet", "meteor", "galaxy", "nebula", "black hole", 
"constellation", "universe", "cosmos", "space", "gravity", "light", "dark matter", "dark energy", "time", "infinity"
]


while True:
    for i in range(5+int(random.random()*20)):
        randomy = random.random()*len(list)
        pyautogui.typewrite(list[int(randomy)])
        pyautogui.typewrite(" ")
    pyautogui.press("enter")
    time.sleep(60+random.random()*300)